### ISSUE TITLE
variable "locales" does not exist

### ISSUE THREAD

**Issue by fatmah** [prestaconcept/PrestaSonataGedmoDoctrineExtensionsBundle#2]
hello,
in "locale_switcher.html.twig" variable "locales" does not exist.
thank you

**Comment by nicolas-bastien** [comment]
Hi you just have to add it in your parametres.yml like :

locales : [fr, en, de]

I will add a doc after my holiday

**Comment by fatmah** [comment]
Hi,happy new year,
 no I have this param in my parameters.yml this exception appear when I try to edit a block from my admin
thank you

**Comment by fatmah** [comment]
Hi , the correct variable name is "presta_sonata_admin_extended_locales" it works for me

**Comment by nicolas-bastien** [comment]
Hi,

Anyway there is a bug there.

First it should not appears in the block edition as locales is set at the
page level.
Sonata new block events as been made so I should refactor this part to have
some thing cleaner.

But I maintains the "locales" parameter is the solution, I guess you don't
have the last version of the bundle.

Just have a look there to checkout :

https://github.com/prestaconcept/PrestaSonataGedmoDoctrineExtensionsBundle/blob/master/Resources/views/CRUD/locale_switcher.html.twig

In 2014 I'll do my best to tag and make proper documentation of all this
bundles

Nico

**Comment by fatmah** [comment]
Hi, no i am using the last version

**Comment by bvleur** [comment]
If it's any help: 
- I do have the latest (commit `f0220585c0943ae749a4f6ab31064bd3a85e5028`) and experience the same issue
- I do have parameters `locales` and `presta_sonata_admin_extended.locales` set to an array of locale codes.
- Adding a parameter `presta_sonata_admin_extended_locales` (as suggested in the comments here) does not help
- Setting the `locales` variable in the template makes everything okay again.

I don't understand enough of this yet to suggest a fix for this.

**Comment by nicolas-bastien** [comment]
Hi, so finally I have time to do this.

So as I said presta_sonata_admin_extended.locales are for admin translations and locales for the front (so your entities too)

What you have to do is to make 'locales' global for twig like this : 

```
twig:
    global:
        locales: %locales%
```

I will make a documentation for this and correct symfony-prestacms too.

Sorry for being so long....
