### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by eko** [prestaconcept/PrestaSonataGedmoDoctrineExtensionsBundle#3]
Hi @nicolas-bastien,

I'm working with @rande, we would like to add a documentation part into `SonataAdminBundle` to explain how to use this bundle to add translation feature.

I pointed out that the documentation link in the bundle `README.md` file displays a 404 error page (http://prestaconcept.github.io/presta-gedmo-doctrine-extensions/).

Do you have a small documentation?

Thank you

**Comment by nicolas-bastien** [comment]
Hi great !

Right now this bundle is not ready to work with sonata block event system.
I think the best is to make it stable and tag a release first.

I'll do my best to do it for the end of next week + doc.

Then I can help you for your documentation, do you agree ?

**Comment by eko** [comment]
Hi,

Great, so we are waiting for a stable version and a little documentation for your bundle.
Let us know when you are ready, thank you!

**Comment by eko** [comment]
@nicolas-bastien,

Do you have some news about this bundle's stable version and its documentation?

**Comment by nicolas-bastien** [comment]
Hi @eko, so I updated the code to fit to new block event system.

You can find the doc here : http://prestaconcept.github.io/presta-gedmo-doctrine-extensions/

I guess you have all you need now ?

I just need to tag admin extended and this bundle now

**Comment by eko** [comment]
Hi @nicolas-bastien,

This is so great, thank you!

We will see how we can integrate it into the `SonataAdminBundle` documentation.

Please let us know when the bundles will be tagged :)

cc @rande

**Comment by eko** [comment]
I close this (old) issue as documentation has been added into https://sonata-project.org/bundles/translation/master/doc/reference/installation.html

Feel free to reopen if needed.

Thank you
