### ISSUE TITLE
Add Doctrine Extension Reference for blending ORM and MongoDB ODM

### ISSUE THREAD

**Issue by webdevilopers** [prestaconcept/PrestaSonataGedmoDoctrineExtensionsBundle#6]
Is this Bundle supposed to integrate the `Reference` extension that allows blending `ORM` and `MongoDB ODM` too?

I am currentely following this example:
https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/references.md

But it won't work from scratch with the `SonataAdminBundle`.

**Comment by nicolas-bastien** [comment]
Hi this bundle is deprecated, this code as been refactored directly in [SonataTranslationBundle](https://github.com/sonata-project/SonataTranslationBundle) and is supposed to handle only translation into SonataAdmin.

**Comment by webdevilopers** [comment]
Thanks for the info @nicolas-bastien !
